// <auto-generated />
using System;
using CariKartSiparisYonetimi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CariKartSiparisYonetimi.Migrations
{
    [DbContext(typeof(CariKartSiparisYonetimiDbContext))]
    [Migration("20261007110501_install")]
    partial class install
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CariKartSiparisYonetimi.Entities.CariKart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CariKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("EPosta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VergiNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CariKod")
                        .IsUnique();

                    b.ToTable("CariKartlar");
                });

            modelBuilder.Entity("CariKartSiparisYonetimi.Entities.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CariKartId")
                        .HasColumnType("int");

                    b.Property<string>("SiparisNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CariKartId");

                    b.HasIndex("SiparisNo")
                        .IsUnique();

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("CariKartSiparisYonetimi.Entities.SiparisDetayi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Miktar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.ToTable("SiparisDetaylari");
                });

            modelBuilder.Entity("CariKartSiparisYonetimi.Entities.Siparis", b =>
                {
                    b.HasOne("CariKartSiparisYonetimi.Entities.CariKart", "CariKart")
                        .WithMany("Siparisler")
                        .HasForeignKey("CariKartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CariKart");
                });

            modelBuilder.Entity("CariKartSiparisYonetimi.Entities.SiparisDetayi", b =>
                {
                    b.HasOne("CariKartSiparisYonetimi.Entities.Siparis", "Siparis")
                        .WithMany("Detaylar")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("CariKartSiparisYonetimi.Entities.CariKart", b =>
                {
                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("CariKartSiparisYonetimi.Entities.Siparis", b =>
                {
                    b.Navigation("Detaylar");
                });
#pragma warning restore 612, 618
        }
    }
}
